# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-PayPal-API
version:      0.62
version_from: lib/Business/PayPal/API.pm
installdirs:  site
requires:
    SOAP::Lite:                    0.67

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
